/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplicationId = IDL.Nat;
export const Application = IDL.Record({
  'id' : ApplicationId,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getApplicationById' : IDL.Func([ApplicationId], [Application], ['query']),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ApplicationId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplicationId = IDL.Nat;
  const Application = IDL.Record({
    'id' : ApplicationId,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getApplicationById' : IDL.Func([ApplicationId], [Application], ['query']),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ApplicationId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };